### ISSUE TITLE
Pairs Trading Forex Question

### ISSUE THREAD

**Issue by cTatu** [yuriak/RLFinance#1]
Hello,
Can I still use the **`PairsTradingTutorial.ipynb`** to trade some other dataset? I have a dataset of a forex pair which contains **O H L C** prices and **Volume** (I can add also some indicators), and I wonder if the example that you're giving in thtat jupyter notebook will work for this dataset.

Thank you!

**Comment by yuriak** [comment]
Hello @cTatu ,
Sorry for the delay. I think it will work, but be careful that two assets in your dataset should better have cointegration relations. You can use the lib [statsmodels](https://github.com/statsmodels/statsmodels) to do a cointegration test. If the p-value<0.05, it is more appropriate to do pairs trading. 

Then, just simply modify the code block of loading data. Good luck :)

**Comment by cTatu** [comment]
My dataset looks like this, so I only have one assets which is the EUR/USD.
![image](https://user-images.githubusercontent.com/37102803/39855350-e1da8298-542b-11e8-9f00-810f30e7299c.png)
 I need one more assets to use this model?

**Comment by yuriak** [comment]
@cTatu I think one asset is also OK, you can treat it as the spread of two different assets. However, you may need to modify the `generate_tech_data` function and only generate technical indicators for one asset.
