### ISSUE TITLE
The train_reward is always nan.

### ISSUE THREAD

**Issue by bingzh8801** [yuriak/RLFinance#2]
Hello,
When I run  PairsTradingTutorial.ipynb to trade, the train_reward is always nan, as follows:
```
train_reward: nan
train_reward: nan
train_reward: nan
train_reward: nan
...
```
I couldn't find what's wrong with the code,could you please help me?
By the way, I wonder the version of packages we used is different,  What versions of packages are you using now ?

Thank you very much.

**Comment by yuriak** [comment]
@bingzh8801 Sorry for the delay, I've just noticed this issue and have replied you via email.
